backend:
  name: github
  repo: tumblenet/go.tumblenet.cu.cc
  base_url: https://tumblenet-api.herokuapp.com

#publish_mode: editorial_workflow
media_folder: "uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "idlink"
    label: "Redirect"
    folder: "_idlink/"
    create: true
    slug: "{{url}}"
    pattern: ['//http:\/\/\w+', "Must have at least 12 characters"]
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "redirect"}
    #  - {label: "Title", name: "title", widget: "string", required="true"}
      - {label: "URL", name: "href", widget: "string", required="true"}
      - {label: "date", name: "date", widget: "date"}
  - name: "link"
    label: "Named Redirect"
    folder: "/_link"
    create: true
    slug: "{{slug}}"
    pattern: ['//http:\/\/\w+', "Must have at least 12 characters"]
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "redirect"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL", name: "href", widget: "string", required="true"}
      - {label: "date", name: "date", widget: "date"}
